use serde::Deserialize;
use std::path::{Path, PathBuf};

/// A single tag kind entry from a plugin's `plugin.toml` manifest.
#[derive(Debug, Deserialize, Clone)]
pub struct ManifestKind {
    pub letter: String,
    pub name: String,
    /// Whether this kind is generated by default (true) or only when explicitly requested (false).
    #[serde(default = "bool_true")]
    pub default: bool,
}

fn bool_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
pub struct PluginManifest {
    pub name: String,
    #[allow(dead_code)]
    pub version: String,
    /// ABI version the plugin targets. Must match the host's `PLUGIN_ABI_VERSION`.
    pub abi_version: u32,
    pub extensions: Vec<String>,
    /// Language name used to look up `--kinds-{lang}` config and to match
    /// `--language-force`.
    pub language: Option<String>,
    /// Additional names accepted by `--language-force` for this plugin's
    /// language. Defaults to empty when omitted from `plugin.toml`.
    #[serde(default)]
    pub aliases: Vec<String>,
    /// Path to the .wasm component file, relative to the directory containing this manifest.
    #[serde(default = "default_wasm_file")]
    pub wasm_file: String,
    /// Optional list of tag kinds the plugin can generate, for `--list-kinds` output.
    pub kinds: Option<Vec<ManifestKind>>,
}

fn default_wasm_file() -> String {
    "plugin.wasm".to_string()
}

impl PluginManifest {
    pub fn wasm_path(&self, manifest_dir: &Path) -> PathBuf {
        manifest_dir.join(&self.wasm_file)
    }
}
