; C++ tag definitions. Actions are compiled to static Rust tables.
((function_definition type: (_) @type declarator: (_) @declarator) @definition (#tt-kind! "function_definition" "function") (#tt-name! @declarator "declarator") (#tt-transform! @declarator "normalize-operator") (#tt-enter-scope! @declarator "function") (#tt-field! "typeref" @type "typename:{}") (#tt-field! "class" @declarator "qualifier:{}") (#tt-emit!))
((function_definition !type declarator: (_) @declarator) @definition (#tt-kind! "function_definition" "function") (#tt-name! @declarator "declarator") (#tt-transform! @declarator "normalize-operator") (#tt-enter-scope! @declarator "function") (#tt-field! "class" @declarator "qualifier:{}") (#tt-emit!))
((declaration type: (_) @type declarator: (function_declarator) @declarator) @definition (#tt-kind! "declaration" "prototype") (#tt-name! @declarator "declarator") (#tt-field! "typeref" @type "typename:{}") (#tt-emit!))
((declaration !type declarator: (function_declarator) @declarator) @definition (#tt-kind! "declaration" "prototype") (#tt-name! @declarator "declarator") (#tt-transform! @declarator "normalize-operator") (#tt-emit!))
((declaration type: (_) @type declarator: (_) @declarator) @definition (#tt-kind! "declaration" "variable") (#tt-name! @declarator "declarator") (#tt-skip-if! @declarator "contains:function_declarator") (#tt-kind-if! "inside:function" "l" "v") (#tt-kind-if! "has-text:extern" "x" "") (#tt-field! "typeref" @type "typename:{}") (#tt-emit-each! @declarator))
((field_declaration) @definition (#tt-kind! "field_declaration" "prototype") (#tt-name! @definition "declarator") (#tt-skip-if! @definition "not-contains:function_declarator") (#tt-transform! @definition "normalize-operator") (#tt-field! "typeref" @definition "type-field:typename:{}") (#tt-emit!))
((field_declaration type: (_) @type declarator: (_) @declarator) @definition (#tt-kind! "field_declaration" "member") (#tt-name! @declarator "declarator") (#tt-skip-if! @declarator "contains:function_declarator") (#tt-field! "typeref" @type "typename:{}") (#tt-emit-each! @declarator))
((class_specifier name: (type_identifier) @name) @definition (#tt-kind! "class_specifier" "class") (#tt-enter-scope! @name "class") (#tt-emit!))
((struct_specifier name: (type_identifier) @name) @definition (#tt-kind! "struct_specifier" "struct") (#tt-enter-scope! @name "struct") (#tt-emit!))
((union_specifier name: (type_identifier) @name) @definition (#tt-kind! "union_specifier" "union") (#tt-enter-scope! @name "union") (#tt-emit!))
((enum_specifier name: (type_identifier) @name base: (_) @base) @definition (#tt-kind! "enum_specifier" "enum") (#tt-enter-scope! @name "enum") (#tt-field! "typeref" @base "typename:{}") (#tt-emit!))
((enum_specifier name: (type_identifier) @name !base) @definition (#tt-kind! "enum_specifier" "enum") (#tt-enter-scope! @name "enum") (#tt-emit!))
((enumerator name: (identifier) @name) @definition (#tt-kind! "enumerator" "enumerator") (#tt-emit!))
((type_definition declarator: (_) @declarator) @definition (#tt-kind! "type_definition" "typedef") (#tt-name! @declarator "declarator") (#tt-emit!))
((preproc_def name: (identifier) @name) @definition (#tt-kind! "preproc_def" "macro") (#tt-emit!))
((preproc_function_def name: (identifier) @name) @definition (#tt-kind! "preproc_function_def" "macro") (#tt-enter-scope! @name "macro") (#tt-emit!))
((preproc_include path: (_) @name) @definition (#tt-kind! "preproc_include" "header") (#tt-transform! @name "trim-delimiters") (#tt-emit!))
((labeled_statement label: (statement_identifier) @label) @definition (#tt-kind! "labeled_statement" "label") (#tt-name! @label "direct") (#tt-emit!))
((namespace_definition name: (namespace_identifier) @name) @definition (#tt-kind! "namespace_definition" "namespace") (#tt-enter-scope! @name "namespace") (#tt-emit!))
((namespace_alias_definition name: (namespace_identifier) @name) @definition (#tt-kind! "namespace_alias_definition" "alias") (#tt-emit!))
((using_declaration) @definition (#tt-kind! "using_declaration" "using") (#tt-name! @definition "using") (#tt-emit!))
((template_declaration (template_parameter_list) @declarator) @definition (#tt-kind! "template_declaration" "parameter") (#tt-name! @declarator "declarator") (#tt-emit-each! @declarator))
((type_parameter_declaration (type_identifier) @name) @definition (#tt-kind! "template_declaration" "parameter") (#tt-emit!))
((optional_type_parameter_declaration (type_identifier) @name) @definition (#tt-kind! "template_declaration" "parameter") (#tt-emit!))
((parameter_declaration type: (_) @type declarator: (_) @declarator) @definition (#tt-kind! "parameter_declaration" "parameter") (#tt-name! @declarator "declarator") (#tt-skip-if! @definition "outside:function") (#tt-field! "typeref" @type "typename:{}") (#tt-emit!))
((preproc_params (identifier) @name) @definition (#tt-kind! "preproc_function_def" "parameter") (#tt-emit-each! @name))
