[package]
name = "treetags-plugin-kotlin"
version = "0.1.0"
edition = "2021"
description = "Kotlin plugin for treetags"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
treetags-plugin-common = { path = "../common", features = ["tree-walker"] }
tree-sitter = "0.26.5"
tree-sitter-kotlin-sg = "=0.4.1"
wit-bindgen = "0.58"
