use crate::parser::{
    c_sharp, cpp, dart, go, java, js, kotlin, objective_c, python, rust, swift, typescript, zig,
    TagKindConfig,
};
use crate::tag::Tag;
use crate::wasm_grammars::GrammarSource;

/// Function pointer type for builtin language tag generators.
pub(crate) type BuiltinGenerateFn = fn(
    &mut tree_sitter::Parser,
    tree_sitter::Language,
    &[u8],
    &str,
    &TagKindConfig,
    &crate::config::Config,
) -> Option<Vec<Tag>>;

/// Full descriptor for a builtin language: name, extensions, kind mappings, generate fn.
pub(crate) struct BuiltinLangDesc {
    pub lang: &'static str,
    /// Alternate names accepted by `--language-force` (and future langmap options),
    /// in addition to `lang`. Case-insensitive at lookup time.
    pub aliases: &'static [&'static str],
    pub extensions: &'static [&'static str],
    /// `fnmatch`-style filename globs (matched against the basename) that select
    /// this language, e.g. `SConstruct` or `*.gyp`. Enables matching files that
    /// have no distinguishing extension.
    pub patterns: &'static [&'static str],
    /// Interpreter names matched against a `#!` shebang line, e.g. `python3`.
    pub interpreters: &'static [&'static str],
    pub kind_defaults: &'static [(&'static [&'static str], &'static str)],
    pub kind_optionals: &'static [(&'static [&'static str], &'static str)],
    /// Content-disambiguation signals keyed by a shared extension: for each
    /// `(ext, signals)`, this language claims `ext` only when one of `signals`
    /// appears in the file content.
    /// eg `.h` is owned outright by C and available to C++ on content evidence.
    pub disambiguation: &'static [(&'static str, &'static [&'static str])],
    pub grammar: GrammarSource,
    pub generate_fn: BuiltinGenerateFn,
}

/// All builtin languages. Priority in tag generation follows array order.
/// Adding a new builtin language requires exactly one new entry here.
pub(crate) static BUILTIN_LANG_DESCRIPTORS: &[BuiltinLangDesc] = &[
    BuiltinLangDesc {
        lang: dart::LANG_NAME,
        aliases: &[],
        extensions: dart::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: dart::KIND_DEFAULTS,
        kind_optionals: dart::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::DART),
        generate_fn: dart::generate,
    },
    BuiltinLangDesc {
        lang: java::LANG_NAME,
        aliases: &[],
        extensions: java::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: java::KIND_DEFAULTS,
        kind_optionals: java::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_java::LANGUAGE.into()),
        generate_fn: java::generate,
    },
    BuiltinLangDesc {
        lang: zig::LANG_NAME,
        aliases: &[],
        extensions: zig::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: zig::KIND_DEFAULTS,
        kind_optionals: zig::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::ZIG),
        generate_fn: zig::generate,
    },
    BuiltinLangDesc {
        lang: swift::LANG_NAME,
        aliases: &[],
        extensions: swift::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: swift::KIND_DEFAULTS,
        kind_optionals: swift::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::SWIFT),
        generate_fn: swift::generate,
    },
    BuiltinLangDesc {
        lang: kotlin::LANG_NAME,
        aliases: &[],
        extensions: kotlin::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: kotlin::KIND_DEFAULTS,
        kind_optionals: kotlin::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::KOTLIN),
        generate_fn: kotlin::generate,
    },
    BuiltinLangDesc {
        lang: c_sharp::LANG_NAME,
        aliases: &["csharp"],
        extensions: c_sharp::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: c_sharp::KIND_DEFAULTS,
        kind_optionals: c_sharp::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_c_sharp::LANGUAGE.into()),
        generate_fn: c_sharp::generate,
    },
    BuiltinLangDesc {
        lang: rust::LANG_NAME,
        aliases: &[],
        extensions: rust::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: rust::KIND_DEFAULTS,
        kind_optionals: rust::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_rust::LANGUAGE.into()),
        generate_fn: rust::generate,
    },
    BuiltinLangDesc {
        lang: go::LANG_NAME,
        aliases: &["golang"],
        extensions: go::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: go::KIND_DEFAULTS,
        kind_optionals: go::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_go::LANGUAGE.into()),
        generate_fn: go::generate,
    },
    BuiltinLangDesc {
        lang: cpp::LANG_NAME,
        aliases: &["cpp", "cxx", "cplusplus"],
        extensions: cpp::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: cpp::KIND_DEFAULTS,
        kind_optionals: cpp::KIND_OPTIONALS,
        // `.h` is owned outright by C; C++ claims it only on C++ markers.
        disambiguation: &[("h", cpp::CPP_DISAMBIG_SIGNALS)],
        grammar: GrammarSource::Bundled(|| tree_sitter_cpp::LANGUAGE.into()),
        generate_fn: cpp::generate,
    },
    // C reuses the C++ parser but is a distinct language with its own kind table.
    BuiltinLangDesc {
        lang: cpp::C_LANG_NAME,
        aliases: &[],
        extensions: cpp::C_LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: cpp::C_KIND_DEFAULTS,
        kind_optionals: cpp::C_KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_cpp::LANGUAGE.into()),
        generate_fn: cpp::generate,
    },
    BuiltinLangDesc {
        lang: objective_c::LANG_NAME,
        aliases: objective_c::LANG_ALIASES,
        extensions: objective_c::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: objective_c::KIND_DEFAULTS,
        kind_optionals: objective_c::KIND_OPTIONALS,
        disambiguation: &[("h", objective_c::DISAMBIG_SIGNALS)],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::OBJECTIVE_C),
        generate_fn: objective_c::generate,
    },
    BuiltinLangDesc {
        lang: js::LANG_NAME,
        aliases: &["js"],
        extensions: js::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &["node", "nodejs"],
        kind_defaults: js::KIND_DEFAULTS,
        kind_optionals: js::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_javascript::LANGUAGE.into()),
        generate_fn: js::generate,
    },
    BuiltinLangDesc {
        lang: python::LANG_NAME,
        aliases: &[],
        extensions: python::LANG_EXTENSIONS,
        patterns: &["SConstruct", "SConscript", "wscript"],
        interpreters: &["python", "python2", "python3"],
        kind_defaults: python::KIND_DEFAULTS,
        kind_optionals: python::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_python::LANGUAGE.into()),
        generate_fn: python::generate,
    },
    BuiltinLangDesc {
        lang: typescript::LANG_NAME,
        aliases: &["ts"],
        extensions: typescript::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: typescript::KIND_DEFAULTS,
        kind_optionals: typescript::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into()),
        generate_fn: typescript::generate,
    },
];
