use crate::parser::{
    c_sharp, cpp, dart, go, java, js, kotlin, objective_c, python, rust, swift, terraform,
    typescript, zig, TagKindConfig,
};
use crate::tag::Tag;
use crate::wasm_grammars::GrammarSource;

/// Function pointer type for extension-field tree walkers.
pub(crate) type WalkerGenerateFn = fn(
    &mut tree_sitter::Parser,
    tree_sitter::Language,
    &[u8],
    &str,
    &TagKindConfig,
    &crate::config::Config,
) -> Option<Vec<Tag>>;

/// One official language registration, independent of its available tag styles.
#[derive(Clone)]
pub(crate) struct LanguageDescriptor {
    pub lang: &'static str,
    /// Alternate names accepted by `--language-force` (and future langmap options),
    /// in addition to `lang`. Case-insensitive at lookup time.
    pub aliases: &'static [&'static str],
    pub extensions: &'static [&'static str],
    /// `fnmatch`-style filename globs (matched against the basename) that select
    /// this language, e.g. `SConstruct` or `*.gyp`. Enables matching files that
    /// have no distinguishing extension.
    pub patterns: &'static [&'static str],
    /// Interpreter names matched against a `#!` shebang line, e.g. `python3`.
    pub interpreters: &'static [&'static str],
    pub kind_defaults: &'static [(&'static [&'static str], &'static str)],
    pub kind_optionals: &'static [(&'static [&'static str], &'static str)],
    /// Content-disambiguation signals keyed by a shared extension: for each
    /// `(ext, signals)`, this language claims `ext` only when one of `signals`
    /// appears in the file content.
    /// eg `.h` is owned outright by C and available to C++ on content evidence.
    pub disambiguation: &'static [(&'static str, &'static [&'static str])],
    pub grammar: GrammarSource,
    pub generate_fn: Option<WalkerGenerateFn>,
    pub query: Option<&'static str>,
    /// Preserve historical user-query overrides only for original query languages.
    pub legacy_query_overrides: bool,
}

#[cfg(test)]
pub(crate) struct LanguageDescriptorTestBuilder(LanguageDescriptor);

#[cfg(test)]
impl LanguageDescriptorTestBuilder {
    pub(crate) fn from_language(lang: &str) -> Self {
        let desc = OFFICIAL_LANGUAGES
            .iter()
            .find(|desc| desc.lang == lang)
            .unwrap_or_else(|| panic!("unknown test language: {lang}"));
        Self(desc.clone())
    }

    pub(crate) fn query(mut self, query: &'static str) -> Self {
        self.0.query = Some(query);
        self
    }

    pub(crate) fn grammar(mut self, grammar: GrammarSource) -> Self {
        self.0.grammar = grammar;
        self
    }

    pub(crate) fn build(self) -> LanguageDescriptor {
        self.0
    }
}

/// All official languages. Source precedence follows array order.
/// Each language is registered once, whether it has one or both implementations.
pub(crate) static OFFICIAL_LANGUAGES: &[LanguageDescriptor] = &[
    LanguageDescriptor {
        lang: dart::LANG_NAME,
        aliases: &[],
        extensions: dart::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: dart::KIND_DEFAULTS,
        kind_optionals: dart::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::DART),
        generate_fn: Some(dart::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: java::LANG_NAME,
        aliases: &[],
        extensions: java::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: java::KIND_DEFAULTS,
        kind_optionals: java::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_java::LANGUAGE.into()),
        generate_fn: Some(java::generate),
        query: Some(tree_sitter_java::TAGS_QUERY),
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: zig::LANG_NAME,
        aliases: &[],
        extensions: zig::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: zig::KIND_DEFAULTS,
        kind_optionals: zig::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::ZIG),
        generate_fn: Some(zig::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: swift::LANG_NAME,
        aliases: &[],
        extensions: swift::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: swift::KIND_DEFAULTS,
        kind_optionals: swift::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::SWIFT),
        generate_fn: Some(swift::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: kotlin::LANG_NAME,
        aliases: &[],
        extensions: kotlin::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: kotlin::KIND_DEFAULTS,
        kind_optionals: kotlin::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::KOTLIN),
        generate_fn: Some(kotlin::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: terraform::LANG_NAME,
        aliases: &[],
        extensions: terraform::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: terraform::KIND_DEFAULTS,
        kind_optionals: terraform::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::TERRAFORM),
        generate_fn: Some(terraform::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: c_sharp::LANG_NAME,
        aliases: &["csharp"],
        extensions: c_sharp::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: c_sharp::KIND_DEFAULTS,
        kind_optionals: c_sharp::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_c_sharp::LANGUAGE.into()),
        generate_fn: Some(c_sharp::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: rust::LANG_NAME,
        aliases: &[],
        extensions: rust::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: rust::KIND_DEFAULTS,
        kind_optionals: rust::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_rust::LANGUAGE.into()),
        generate_fn: Some(rust::generate),
        query: Some(tree_sitter_rust::TAGS_QUERY),
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: go::LANG_NAME,
        aliases: &["golang"],
        extensions: go::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: go::KIND_DEFAULTS,
        kind_optionals: go::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_go::LANGUAGE.into()),
        generate_fn: Some(go::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: cpp::LANG_NAME,
        aliases: &["cpp", "cxx", "cplusplus"],
        extensions: cpp::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: cpp::KIND_DEFAULTS,
        kind_optionals: cpp::KIND_OPTIONALS,
        // `.h` is owned outright by C; C++ claims it only on C++ markers.
        disambiguation: &[("h", cpp::CPP_DISAMBIG_SIGNALS)],
        grammar: GrammarSource::Bundled(|| tree_sitter_cpp::LANGUAGE.into()),
        generate_fn: Some(cpp::generate),
        query: None,
        legacy_query_overrides: false,
    },
    // C reuses the C++ parser but is a distinct language with its own kind table.
    LanguageDescriptor {
        lang: cpp::C_LANG_NAME,
        aliases: &[],
        extensions: cpp::C_LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: cpp::C_KIND_DEFAULTS,
        kind_optionals: cpp::C_KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_cpp::LANGUAGE.into()),
        generate_fn: Some(cpp::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: objective_c::LANG_NAME,
        aliases: objective_c::LANG_ALIASES,
        extensions: objective_c::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: objective_c::KIND_DEFAULTS,
        kind_optionals: objective_c::KIND_OPTIONALS,
        disambiguation: &[("h", objective_c::DISAMBIG_SIGNALS)],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::OBJECTIVE_C),
        generate_fn: Some(objective_c::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: js::LANG_NAME,
        aliases: &["js"],
        extensions: js::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &["node", "nodejs"],
        kind_defaults: js::KIND_DEFAULTS,
        kind_optionals: js::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_javascript::LANGUAGE.into()),
        generate_fn: Some(js::generate),
        query: Some(tree_sitter_javascript::TAGS_QUERY),
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: python::LANG_NAME,
        aliases: &[],
        extensions: python::LANG_EXTENSIONS,
        patterns: &["SConstruct", "SConscript", "wscript"],
        interpreters: &["python", "python2", "python3"],
        kind_defaults: python::KIND_DEFAULTS,
        kind_optionals: python::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_python::LANGUAGE.into()),
        generate_fn: Some(python::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: typescript::LANG_NAME,
        aliases: &["ts"],
        extensions: typescript::LANG_EXTENSIONS,
        patterns: &[],
        interpreters: &[],
        kind_defaults: typescript::KIND_DEFAULTS,
        kind_optionals: typescript::KIND_OPTIONALS,
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into()),
        generate_fn: Some(typescript::generate),
        query: None,
        legacy_query_overrides: false,
    },
    LanguageDescriptor {
        lang: "ruby",
        aliases: &[],
        extensions: &["rb"],
        patterns: &[
            "Rakefile",
            "Gemfile",
            "Guardfile",
            "Vagrantfile",
            "Podfile",
            "Berksfile",
            "Brewfile",
            "Capfile",
            "*.gemspec",
            "*.podspec",
            "*.rake",
        ],
        interpreters: &["ruby"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_ruby::LANGUAGE.into()),
        generate_fn: None,
        query: Some(tree_sitter_ruby::TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "ocaml",
        aliases: &[],
        extensions: &["ml"],
        patterns: &[],
        interpreters: &[],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Wasm(&crate::wasm_grammars::OCAML),
        generate_fn: None,
        query: Some(include_str!("../queries/ocaml.scm")),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "php",
        aliases: &[],
        extensions: &["php"],
        patterns: &[],
        interpreters: &["php"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_php::LANGUAGE_PHP.into()),
        generate_fn: None,
        query: Some(tree_sitter_php::TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "elixir",
        aliases: &[],
        extensions: &["ex"],
        patterns: &[],
        interpreters: &[],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_elixir::LANGUAGE.into()),
        generate_fn: None,
        query: Some(tree_sitter_elixir::TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "lua",
        aliases: &[],
        extensions: &["lua"],
        patterns: &[],
        interpreters: &["lua"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_lua::LANGUAGE.into()),
        generate_fn: None,
        query: Some(tree_sitter_lua::TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "shell",
        aliases: &["sh", "bash"],
        extensions: &["sh", "bash"],
        patterns: &[
            ".bashrc",
            ".bash_profile",
            ".bash_logout",
            ".zshrc",
            ".zprofile",
            ".zshenv",
            ".profile",
            "PKGBUILD",
            "*.zsh",
        ],
        interpreters: &["sh", "bash", "dash", "zsh", "ksh"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_bash::LANGUAGE.into()),
        generate_fn: None,
        query: Some(crate::queries::BASH_TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "scala",
        aliases: &[],
        extensions: &["scala"],
        patterns: &[],
        interpreters: &["scala"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_scala::LANGUAGE.into()),
        generate_fn: None,
        query: Some(crate::queries::SCALA_TAGS_QUERY),
        legacy_query_overrides: true,
    },
    LanguageDescriptor {
        lang: "julia",
        aliases: &[],
        extensions: &["jl"],
        patterns: &[],
        interpreters: &["julia"],
        kind_defaults: &[],
        kind_optionals: &[],
        disambiguation: &[],
        grammar: GrammarSource::Bundled(|| tree_sitter_julia::LANGUAGE.into()),
        generate_fn: None,
        query: Some(crate::queries::JULIA_TAGS_QUERY),
        legacy_query_overrides: true,
    },
];
