mod config;
pub use config::Config;
mod tag;
pub use tag::parse_tag_file;
pub use tag::Tag;
mod parser;
pub use parser::Parser;

pub mod c;
pub mod cpp;
pub mod elixir;
pub mod go;
pub mod java;
pub mod js;
pub mod lua;
pub mod ocaml;
pub mod php;
pub mod python;
pub mod ruby;
pub mod rust;
pub mod typescript;
