; Objective-C is a superset of the C tag set. These declarative patterns feed
; kind/role generation; the shared island engine performs the structural walk.
((function_definition declarator: (_) @declarator) @definition (#tt-kind! "function_definition" "function") (#tt-name! @declarator "declarator") (#tt-enter-scope! @declarator "function") (#tt-emit!))
((declaration declarator: (function_declarator) @declarator) @definition (#tt-kind! "declaration" "prototype") (#tt-name! @declarator "declarator") (#tt-emit!))
((declaration declarator: (_) @declarator) @definition (#tt-kind! "declaration" "variable") (#tt-name! @declarator "declarator") (#tt-kind-if! "inside:function" "l" "v") (#tt-kind-if! "has-text:extern" "x" "") (#tt-emit-each! @declarator))
((field_declaration declarator: (_) @declarator) @definition (#tt-kind! "field_declaration" "member") (#tt-name! @declarator "declarator") (#tt-emit-each! @declarator))
((struct_specifier name: (_) @name) @definition (#tt-kind! "struct_specifier" "struct") (#tt-enter-scope! @name "struct") (#tt-emit!))
((union_specifier name: (_) @name) @definition (#tt-kind! "union_specifier" "union") (#tt-enter-scope! @name "union") (#tt-emit!))
((enum_specifier name: (_) @name) @definition (#tt-kind! "enum_specifier" "enum") (#tt-enter-scope! @name "enum") (#tt-emit!))
((enumerator name: (_) @name) @definition (#tt-kind! "enumerator" "enumerator") (#tt-emit!))
((type_definition declarator: (_) @declarator) @definition (#tt-kind! "type_definition" "typedef") (#tt-name! @declarator "declarator") (#tt-emit!))
((preproc_def name: (_) @name) @definition (#tt-kind! "preproc_def" "macro") (#tt-emit!))
((preproc_function_def name: (_) @name) @definition (#tt-kind! "preproc_function_def" "macro") (#tt-enter-scope! @name "macro") (#tt-emit!))
((preproc_include path: (_) @name) @definition (#tt-kind! "preproc_include" "header") (#tt-transform! @name "trim-delimiters") (#tt-emit!))
((class_interface (identifier) @name) @definition (#tt-kind! "class_interface" "interface") (#tt-enter-scope! @name "interface") (#tt-emit!))
((class_interface category: (identifier) @category (identifier) @name) @definition (#tt-kind! "class_interface" "category") (#tt-emit!))
((class_implementation (identifier) @name) @definition (#tt-kind! "class_implementation" "implementation") (#tt-enter-scope! @name "implementation") (#tt-emit!))
((class_implementation category: (identifier) @category (identifier) @name) @definition (#tt-kind! "class_implementation" "category") (#tt-emit!))
((protocol_declaration (identifier) @name) @definition (#tt-kind! "protocol_declaration" "protocol") (#tt-enter-scope! @name "protocol") (#tt-emit!))
((method_declaration (identifier) @name) @definition (#tt-kind! "method_declaration" "method") (#tt-emit!))
((property_declaration (_) @name) @definition (#tt-kind! "property_declaration" "property") (#tt-emit!))
((instance_variable (_) @name) @definition (#tt-kind! "instance_variable" "ivar") (#tt-emit!))
((labeled_statement label: (_) @label) @definition (#tt-kind! "labeled_statement" "label") (#tt-name! @label "direct") (#tt-emit!))
((parameter_declaration declarator: (_) @declarator) @definition (#tt-kind! "parameter_declaration" "parameter") (#tt-name! @declarator "declarator") (#tt-emit!))
((preproc_params (identifier) @name) @definition (#tt-kind! "preproc_function_def" "parameter") (#tt-emit-each! @name))
