[package]
name = "treetags-plugin-zig"
version = "0.1.0"
edition = "2021"
description = "Zig plugin for treetags"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
treetags-plugin-common = { path = "../common", features = ["tree-walker"] }
tree-sitter = "0.26.5"
tree-sitter-zig = "1.1.2"
wit-bindgen = "0.58"
